/**
 * weaveGraphState.ts
 *
 * Typed LangGraph state annotation for the Weaver agent loop.
 * Uses @langchain/langgraph's Annotation API for graph-native state management
 * with correct reducer semantics per channel.
 */

import { Annotation } from '@langchain/langgraph';
import { BaseMessage } from '@langchain/core/messages';
import type {
  WeavePlanRequest,
  WeavePlanResult,
  WeaveErrorCategory,
  WeaveReActStep,
} from '../vault-contract';
import type { WeaveContextSnapshot } from './weaveContextService';
import type { WeaveFullModelProfile } from './weaveModelProfiles';

// ── Route identifiers ─────────────────────────────────────────────────────────

/**
 * Routing decisions emitted by nodes and consumed by conditional edges.
 * Null means "no pending decision" (terminal or not yet set).
 */
export type WeaveAgentRoute =
  | 'execute-tool'
  | 'finalize'
  | 'repair-syntactic'
  | 'repair-semantic'
  | 'repair-schema'
  | 'repair-exhaustion'
  | 'fail';

// ── Usage merge helper ────────────────────────────────────────────────────────

function sumOptional(a?: number, b?: number): number | undefined {
  if (a === undefined && b === undefined) return undefined;
  return (a ?? 0) + (b ?? 0);
}

function mergeUsage(
  existing: WeavePlanResult['usage'],
  incoming: WeavePlanResult['usage'],
): WeavePlanResult['usage'] {
  if (!existing && !incoming) return undefined;
  return {
    promptTokens: sumOptional(existing?.promptTokens, incoming?.promptTokens),
    completionTokens: sumOptional(existing?.completionTokens, incoming?.completionTokens),
    totalTokens: sumOptional(existing?.totalTokens, incoming?.totalTokens),
  };
}

// ── State annotation ──────────────────────────────────────────────────────────

/**
 * Full LangGraph state for the Weaver agent loop.
 *
 * Channel semantics:
 *   - messages:          append  — each node appends new messages; never overwrites.
 *   - accumulatedUsage:  merge   — token counts accumulate across LLM turns.
 *   - all other fields:  replace — last write wins (default LangGraph semantics).
 */
export const WeaveAgentStateAnnotation = Annotation.Root({
  // ── Inputs (set before graph.invoke; immutable during the run) ──────────────
  request: Annotation<WeavePlanRequest | null>({
    value: (_, b) => b,
    default: () => null,
  }),
  contextSnapshot: Annotation<WeaveContextSnapshot | null>({
    value: (_, b) => b,
    default: () => null,
  }),
  modelProfile: Annotation<WeaveFullModelProfile | null>({
    value: (_, b) => b,
    default: () => null,
  }),
  resolvedModel: Annotation<string>({
    value: (_, b) => b,
    default: () => '',
  }),
  startTimeMs: Annotation<number>({
    value: (_, b) => b,
    default: () => 0,
  }),

  // ── Conversation state ──────────────────────────────────────────────────────
  /**
   * The full message history. Uses an append reducer so every node
   * that returns { messages: [...] } extends the history rather than replacing it.
   */
  messages: Annotation<BaseMessage[]>({
    reducer: (existing, incoming) => existing.concat(incoming),
    default: () => [],
  }),

  // ── Execution counters ──────────────────────────────────────────────────────
  /** Number of read-only tool calls executed so far. */
  toolCallCount: Annotation<number>({
    value: (_, b) => b,
    default: () => 0,
  }),
  /** Number of repair turns attempted (syntactic + semantic + schema). */
  repairAttemptCount: Annotation<number>({
    value: (_, b) => b,
    default: () => 0,
  }),

  // ── Transient inter-node communication ──────────────────────────────────────
  /**
   * Routing decision set by the current node and consumed by conditional edges.
   * Nodes must set this when they want to influence the next node selection.
   */
  pendingRoute: Annotation<WeaveAgentRoute | null>({
    value: (_, b) => b,
    default: () => null,
  }),
  /** Tool name to execute (set by callModel when pendingRoute = execute-tool). */
  pendingToolName: Annotation<string | null>({
    value: (_, b) => b,
    default: () => null,
  }),
  /** Thought generated by the agent during this step. */
  pendingThought: Annotation<string | null>({
    value: (_, b) => b,
    default: () => null,
  }),
  /** Tool arguments (set alongside pendingToolName). */
  pendingToolArgs: Annotation<Record<string, unknown> | null>({
    value: (_, b) => b,
    default: () => null,
  }),
  /** Raw plan data extracted from the model's final action (set before validate). */
  pendingPlanData: Annotation<unknown>({
    value: (_, b) => b,
    default: () => null,
  }),
  /** Raw model response text, stored for repair and logging. */
  lastRawContent: Annotation<string>({
    value: (_, b) => b,
    default: () => '',
  }),

  // ── Accumulated metrics ─────────────────────────────────────────────────────
  /**
   * Token usage merged from all LLM calls in this run.
   * Uses a custom merge reducer so each callModel turn adds to the total.
   */
  accumulatedUsage: Annotation<WeavePlanResult['usage']>({
    reducer: mergeUsage,
    default: () => undefined,
  }),

  // ── Terminal outputs ────────────────────────────────────────────────────────
  /** Validated result, set on successful completion. */
  result: Annotation<WeavePlanResult | null>({
    value: (_, b) => b,
    default: () => null,
  }),
  /** History of the Thought-Action-Observation steps during the run. */
  trace: Annotation<WeaveReActStep[]>({
    reducer: (existing, incoming) => (existing || []).concat(incoming || []),
    default: () => [],
  }),
  /** Human-readable error description, set on failure. */
  errorMessage: Annotation<string | null>({
    value: (_, b) => b,
    default: () => null,
  }),
  /** Machine-readable error category, set on failure. */
  errorCategory: Annotation<WeaveErrorCategory | null>({
    value: (_, b) => b,
    default: () => null,
  }),
});

export type WeaveAgentState = typeof WeaveAgentStateAnnotation.State;
